# @author Madhavan Sridharan
name: Prepare Version Tag

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create version bump branch
        id: create_branch
        run: |
          git fetch origin main
          git checkout -b release/bump-tag-version origin/main
          npm version ${{ github.event.inputs.release_type }} -m "chore(release): bump tag version to %s"
          git push origin -u release/bump-tag-version --follow-tags
